name: pyFlika
markdown: kramdown
highlighter: rouge
docs:
  - top-level: Widgets
    nested-docs:
      - nested: window
        site: window.html
      - nested: trace
        site: trace.html
      - nested: roi
        site: roi.html
  - top-level: Processes
    nested-docs:
      - nested: file_
        site: file_.html
      - nested: BaseProcess
        site: BaseProcess.html
      - nested: Other
        site: flika.html
