name: pyFlika
markdown: kramdown
highlighter: rouge
documentation:
  - top: Widgets
    nested-pages:
      - nested: window
        site: window.html
      - nested: trace
        site: trace.html
      - nested: roi
        site: roi.html
  - top: Processes
    nested-pages:
      - nested: file_
        site: file_.html
      - nested: BaseProcess
        site: BaseProcess.html
      - nested: Other
        site: flika.html
